(()=>{
if(window.__AGP_V70)return;window.__AGP_V70=true;
const HKEY='inventoryLeadHistory',SKEY='inventoryLeadSales',AKEY='inventoryLeadAccepted',OKEY='inventoryLeadOutreach';
const parse=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const leads=()=>window.INVENTORY_LEADS||[];
const leadBy=id=>leads().find(x=>x.id===id);
const today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)};
const money=n=>`S/ ${Math.round(Number(n)||0).toLocaleString('es-PE')}`;
function addHistory(id,type,text,meta={}){const h=parse(HKEY);h[id]=h[id]||[];h[id].unshift({at:new Date().toISOString(),type,text,...meta});h[id]=h[id].slice(0,80);save(HKEY,h)}
function wrap(name,fn){const old=window[name];if(typeof old!=='function'||old.__v70)return;const n=function(...args){const before=parse(OKEY)[args[0]];const r=old.apply(this,args);try{fn(args,before)}catch{};setTimeout(refresh,70);return r};n.__v70=true;window[name]=n}
function installHooks(){wrap('markSent',([id])=>addHistory(id,'message','Mensaje inicial enviado por WhatsApp'));wrap('setStage',([id,s],before)=>{if(before!==s)addHistory(id,'status',`Estado comercial: ${s}`)});wrap('pickReply',([id,type])=>addHistory(id,'reply',`Respuesta clasificada: ${type}`));wrap('acceptLead',([id])=>addHistory(id,'pipeline','Prospecto pasado a seguimiento'));wrap('saveReply',([id])=>addHistory(id,'reply','Respuesta comercial guardada'))}
function ensureDialog(){if(document.getElementById('v7Dialog'))return;const d=document.createElement('dialog');d.id='v7Dialog';d.innerHTML='<div class="sheet" id="v7Sheet"></div>';document.body.appendChild(d)}
function schedule(id,days){const a=parse(AKEY),l=leadBy(id);a[id]=a[id]||{acceptedAt:today(),stage:'Interesado',probability:60,quote:'',notes:'',contactName:'',lastContact:today()};const dt=new Date();dt.setDate(dt.getDate()+days);a[id].nextDate=new Date(dt-dt.getTimezoneOffset()*60000).toISOString().slice(0,10);a[id].nextAction='Dar seguimiento por WhatsApp';a[id].lastContact=today();save(AKEY,a);addHistory(id,'followup',`Seguimiento programado para ${a[id].nextDate}`);alert(`Seguimiento de ${l?.company||'prospecto'} programado.`);setTimeout(()=>location.reload(),120)}
function quickActions(){document.querySelectorAll('#grid .card').forEach(card=>{if(card.querySelector('.v7Quick'))return;const name=card.querySelector('.name')?.textContent?.trim(),l=leads().find(x=>x.company===name);if(!l)return;const box=document.createElement('div');box.className='v7Quick';box.innerHTML=`<button data-s="Mensaje enviado">Enviado</button><button data-s="Respondió">Respondió</button><button data-s="Interesado">Interesado</button><button data-s="No interesado">Descartar</button><button class="v7Later">+2 días</button>`;box.onclick=e=>{const b=e.target.closest('button');if(!b)return;e.preventDefault();e.stopPropagation();if(b.dataset.s){window.setStage?.(l.id,b.dataset.s);if(b.dataset.s==='Mensaje enviado')addHistory(l.id,'message','Mensaje marcado como enviado desde acción rápida')}else if(b.classList.contains('v7Later'))schedule(l.id,2)};card.appendChild(box);applySemaphore(card,l.id)})}
function applySemaphore(card,id){const a=parse(AKEY)[id],o=parse(OKEY)[id]||'Sin contactar';card.classList.remove('v7Red','v7Amber','v7Green');if(a?.nextDate){const diff=Math.ceil((new Date(a.nextDate+'T23:59:59')-new Date())/86400000);card.classList.add(diff<0?'v7Red':diff===0?'v7Amber':'v7Green')}else if(['Respondió','Interesado','Aceptó propuesta','Seguimiento'].includes(o))card.classList.add('v7Green')}
function funnel(){const d=document.getElementById('agpDashboard');if(!d||d.querySelector('.v7Funnel'))return;const o=parse(OKEY),a=parse(AKEY),s=parse(SKEY),ls=leads();const total=ls.length,contacted=ls.filter(l=>(o[l.id]||'Sin contactar')!=='Sin contactar').length,replied=ls.filter(l=>['Respondió','Interesado','Aceptó propuesta','Seguimiento'].includes(o[l.id]||'')).length,interested=ls.filter(l=>['Interesado','Aceptó propuesta','Seguimiento'].includes(o[l.id]||'')).length,quoted=Object.values(a).filter(x=>Number(x?.quote)>0).length,closed=Object.values(s).filter(x=>Number(x?.sale)>0).length;const arr=[['Base',total],['Contactados',contacted],['Respondieron',replied],['Interesados',interested],['Cotizados',quoted],['Clientes',closed]];const el=document.createElement('div');el.className='v7Funnel';el.innerHTML=`<div class="v7Title"><div><span class="miniLabel">Embudo comercial</span><b>Conversión real</b></div><button id="v7Metrics">Ver análisis</button></div><div class="v7FunnelRow">${arr.map(([n,v],i)=>`<div><b>${v}</b><span>${n}</span>${i?`<small>${arr[i-1][1]?Math.round(v/arr[i-1][1]*100):0}%</small>`:''}</div>`).join('')}</div>`;d.appendChild(el);el.querySelector('#v7Metrics').onclick=openAnalysis}
function sectorStats(){const o=parse(OKEY),groups={};leads().forEach(l=>{const g=groups[l.sector]||(groups[l.sector]={n:0,c:0,r:0,i:0});g.n++;const st=o[l.id]||'Sin contactar';if(st!=='Sin contactar')g.c++;if(['Respondió','Interesado','Aceptó propuesta','Seguimiento'].includes(st))g.r++;if(['Interesado','Aceptó propuesta','Seguimiento'].includes(st))g.i++});return Object.entries(groups).map(([sector,g])=>({sector,...g,response:g.c?g.r/g.c:0,interest:g.c?g.i/g.c:0})).sort((a,b)=>b.interest-a.interest||b.response-a.response)}
function openAnalysis(){ensureDialog();const sh=document.getElementById('v7Sheet'),sales=parse(SKEY),vals=Object.values(sales),revenue=vals.reduce((x,y)=>x+(Number(y.sale)||0),0),cost=vals.reduce((x,y)=>x+(Number(y.cost)||0),0),profit=revenue-cost,top=sectorStats().slice(0,6);sh.innerHTML=`<div class="sheetTop"><div><h2>Rendimiento comercial</h2><div class="meta">Datos reales generados por tu actividad en el CRM.</div></div><button class="close" onclick="v7Dialog.close()">×</button></div><div class="v7Money"><div><span>Ventas registradas</span><b>${money(revenue)}</b></div><div><span>Costos</span><b>${money(cost)}</b></div><div><span>Utilidad</span><b>${money(profit)}</b></div></div><div class="block"><h3>Rubros con mejor respuesta</h3><div class="v7Sector">${top.map(x=>`<div><span>${x.sector}</span><b>${Math.round(x.response*100)}% respuesta</b><small>${Math.round(x.interest*100)}% interés · ${x.c} contactados</small></div>`).join('')||'<p>Aún no hay datos suficientes.</p>'}</div></div>`;document.getElementById('v7Dialog').showModal()}
function openHistory(id){ensureDialog();const l=leadBy(id),h=parse(HKEY)[id]||[];document.getElementById('v7Sheet').innerHTML=`<div class="sheetTop"><div><h2>${l?.company||'Historial'}</h2><div class="meta">Cronología comercial</div></div><button class="close" onclick="v7Dialog.close()">×</button></div><div class="v7Timeline">${h.length?h.map(x=>`<div class="v7Event"><i></i><div><b>${x.text}</b><span>${new Date(x.at).toLocaleString('es-PE',{dateStyle:'medium',timeStyle:'short'})}</span></div></div>`).join(''):'<div class="empty">Aún no hay movimientos registrados para este prospecto.</div>'}</div>`;document.getElementById('v7Dialog').showModal()}
function salesButtons(){document.querySelectorAll('#acceptedGrid article,#acceptedGrid .card').forEach(card=>{if(card.querySelector('.v7SaleBtn'))return;const name=card.querySelector('.name,h3,h2')?.textContent?.trim(),l=leads().find(x=>x.company===name);if(!l)return;const b=document.createElement('button');b.className='btn v7SaleBtn';b.textContent='Registrar venta';b.onclick=()=>openSale(l.id);card.appendChild(b)})}
function openSale(id){ensureDialog();const l=leadBy(id),s=parse(SKEY)[id]||{},a=parse(AKEY)[id]||{};document.getElementById('v7Sheet').innerHTML=`<div class="sheetTop"><div><h2>Registrar resultado</h2><div class="meta">${l?.company||''}</div></div><button class="close" onclick="v7Dialog.close()">×</button></div><div class="block v7SaleForm"><label>Monto final cobrado S/<input id="v7Sale" class="ctl" type="number" min="0" value="${s.sale||a.quote||''}"></label><label>Costo real del servicio S/<input id="v7Cost" class="ctl" type="number" min="0" value="${s.cost||''}"></label><label>Fecha del servicio<input id="v7Date" class="ctl" type="date" value="${s.date||today()}"></label><button class="btn primary wide" id="v7SaveSale">Guardar resultado</button><div id="v7Profit" class="v7Profit"></div></div>`;const calc=()=>{const sale=Number(document.getElementById('v7Sale').value)||0,cost=Number(document.getElementById('v7Cost').value)||0,p=sale-cost,margin=sale?Math.round(p/sale*100):0;document.getElementById('v7Profit').textContent=`Utilidad estimada: ${money(p)} · Margen real ${margin}%`};['v7Sale','v7Cost'].forEach(x=>document.getElementById(x).oninput=calc);calc();document.getElementById('v7SaveSale').onclick=()=>{const all=parse(SKEY);all[id]={sale:Number(document.getElementById('v7Sale').value)||0,cost:Number(document.getElementById('v7Cost').value)||0,date:document.getElementById('v7Date').value};save(SKEY,all);addHistory(id,'sale',`Venta registrada por ${money(all[id].sale)} · utilidad ${money(all[id].sale-all[id].cost)}`);document.getElementById('v7Dialog').close();refresh()};document.getElementById('v7Dialog').showModal()}
function smartScores(){const stats=sectorStats(),m=Object.fromEntries(stats.map(x=>[x.sector,x]));const o=parse(OKEY);leads().forEach(l=>{const st=m[l.sector],base=Number(l.closeScore||l.score||80),bonus=st&&st.c>=2?Math.round(st.response*8+st.interest*12):0,status=o[l.id]||'Sin contactar',activity=status==='Respondió'?8:status==='Interesado'?14:status==='Aceptó propuesta'||status==='Seguimiento'?18:0;l.v7Score=Math.min(100,base+bonus+activity)})}
function refresh(){smartScores();quickActions();salesButtons();funnel()}
function boot(){installHooks();refresh();document.addEventListener('click',e=>{if(e.target.closest?.('#grid,#acceptedGrid,#agpDashboard'))setTimeout(refresh,80)});document.addEventListener('change',()=>setTimeout(refresh,80));window.addEventListener('storage',refresh);setInterval(refresh,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();