(()=>{if(window.__AGP_PENDING_V99)return;window.__AGP_PENDING_V99=true;
const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return{}}};
const leads=()=>window.INVENTORY_LEADS||[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
function items(){const o=read('inventoryLeadOutreach'),a=read('inventoryLeadAccepted'),ls=leads(),out=[];const map=new Map(ls.map(l=>[l.id,l]));
 ls.forEach(l=>{const s=o[l.id]||'Sin contactar';if(s==='Respondió')out.push({id:l.id,type:'reply',priority:1,title:l.company,meta:'Respondió · requiere atención',action:'Abrir conversación'});else if(s==='Interesado'&&!a[l.id])out.push({id:l.id,type:'interest',priority:2,title:l.company,meta:'Interesado · avanzar propuesta',action:'Continuar'});});
 Object.entries(a).forEach(([id,x])=>{if(!x)return;const l=map.get(id),name=l?.company||x.company||'Prospecto';if(x.stage==='Cerrado')return;if(x.nextDate&&x.nextDate<today())out.push({id,type:'overdue',priority:0,title:name,meta:`Seguimiento vencido · ${x.nextDate}`,action:'Ver seguimiento'});else if(x.nextDate===today())out.push({id,type:'today',priority:1,title:name,meta:'Seguimiento para hoy',action:'Ver seguimiento'});if(['Interesado','Por cotizar'].includes(x.stage||'')&&!(Number(x.quote)>0))out.push({id,type:'quote',priority:2,title:name,meta:'Falta preparar cotización',action:'Cotizar'});if(x.stage==='Cotización enviada'&&!x.nextDate)out.push({id,type:'follow',priority:3,title:name,meta:'Cotización enviada · sin próxima fecha',action:'Programar seguimiento'});if(x.stage==='Cobro pendiente')out.push({id,type:'money',priority:1,title:name,meta:'Cobro pendiente',action:'Ver seguimiento'});});
 const seen=new Set();return out.sort((a,b)=>a.priority-b.priority).filter(x=>{const k=x.id+'|'+x.type;if(seen.has(k))return false;seen.add(k);return true})}
function count(){return items().length}
function updateBadge(){const n=count(),b=document.getElementById('mobilePendingBadge');if(b){b.textContent=n?String(Math.min(n,99)):'';b.hidden=!n}}
function openLead(id){document.querySelector('.moduleBtn[data-module="prospects"]')?.click();setTimeout(()=>window.openLead?.(id),80)}
function act(x){if(x.type==='quote'){document.querySelector('.moduleBtn[data-module="quote"]')?.click();setTimeout(()=>{const q=document.getElementById('quoteLead');if(q){q.value=x.id;q.dispatchEvent(new Event('change',{bubbles:true}))}},80)}else if(['overdue','today','follow','money'].includes(x.type)){document.querySelector('.moduleBtn[data-module="accepted"]')?.click();setTimeout(()=>{const c=[...document.querySelectorAll('#acceptedGrid .acceptedCard')].find(el=>el.textContent.includes(x.title));c?.scrollIntoView({behavior:'smooth',block:'center'})},120)}else openLead(x.id)}
function show(){let d=document.getElementById('pendingDialog99');if(!d){d=document.createElement('dialog');d.id='pendingDialog99';d.innerHTML='<div class="sheet pendingSheet99"><div class="sheetTop"><div><span class="miniLabel">Centro de acción</span><h2>Pendientes</h2><div class="meta">Lo que necesita tu atención ahora.</div></div><button class="close" data-pclose aria-label="Cerrar">×</button></div><div class="pendingList99"></div></div>';document.body.appendChild(d);d.querySelector('[data-pclose]').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close();const b=e.target.closest('[data-pidx]');if(!b)return;const x=items()[Number(b.dataset.pidx)];if(x){d.close();act(x)}})}const arr=items(),box=d.querySelector('.pendingList99');box.innerHTML=arr.length?arr.map((x,i)=>`<button class="pendingItem99 p-${x.type}" data-pidx="${i}"><span class="pendingDot99"></span><span class="pendingText99"><b>${esc(x.title)}</b><small>${esc(x.meta)}</small></span><span class="pendingGo99">${esc(x.action)} <i>›</i></span></button>`).join(''):'<div class="pendingEmpty99"><b>Todo al día</b><span>No tienes acciones comerciales urgentes por ahora.</span></div>';d.showModal();setTimeout(()=>window.dispatchEvent(new Event('agpPendingUpdated')),0)}
window.AGP_PENDING={show,count,updateBadge};
function boot(){updateBadge();window.addEventListener('storage',updateBadge);document.addEventListener('change',()=>setTimeout(updateBadge,80));document.addEventListener('click',()=>setTimeout(updateBadge,120));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();