(()=>{
if(window.__AGP_PROSPECTING_V78)return;window.__AGP_PROSPECTING_V78=true;
const KEY='inventoryLeadVariants';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
function kind(l){const s=(l?.sector||'').toLowerCase();if(s.includes('ferreter'))return'ferretería';if(s.includes('minimarket')||s.includes('abarrote'))return'minimarket';if(s.includes('farm')||s.includes('botica'))return'botica';if(s.includes('repuesto'))return'negocio de repuestos';if(s.includes('mascota'))return'tienda de mascotas';if(s.includes('tecnolog'))return'tienda de tecnología';return'negocio'}
const P={
 A:{name:'Consulta natural ⭐',help:'Recomendada. Abre conversación sin parecer publicidad masiva.',text:l=>`Hola 👋, ¿qué tal? Te escribo de AGP. Estamos apoyando a negocios con sus inventarios físicos para conocer mejor su stock y detectar posibles diferencias. Quería hacerte una consulta breve: ¿ustedes realizan inventarios periódicamente en su ${kind(l)}?`},
 B:{name:'Detectar problema',help:'Hace que el negocio piense en diferencias entre su sistema y el stock real.',text:l=>`Hola 👋, te contacto de AGP. Una consulta: ¿actualmente tienen alguna forma de comprobar si el stock registrado coincide realmente con lo que tienen físicamente? Nosotros apoyamos a negocios con el conteo y revisión de inventarios, y quería saber si es algo que podría serles útil.`},
 C:{name:'Lanzamiento 🚀',help:'Presenta la promoción sin competir solamente por precio.',text:l=>`Hola 👋, soy de AGP. Estamos abriendo agenda para nuevos servicios de inventario y contamos con una tarifa especial de lanzamiento. Realizamos el conteo físico, consolidamos los resultados y apoyamos en la identificación de diferencias de stock. Si me indicas aproximadamente cuántos productos manejan y en qué distrito se encuentran, puedo orientarte con una cotización sin compromiso.`},
 D:{name:'Diferencias de stock',help:'Gancho directo para negocios donde faltantes y sobrantes pueden ser un problema.',text:l=>`Hola 👋, te escribo de AGP. Estamos apoyando a negocios a identificar faltantes, sobrantes y diferencias de stock mediante inventarios físicos. Quería hacerte una consulta rápida: ¿hace cuánto realizaron su último inventario?`},
 E:{name:'Buscar encargado',help:'Ideal para WhatsApp generales. Primero busca llegar a quien toma la decisión.',text:l=>`Hola 👋, ¿qué tal? Soy de AGP. ¿Con quién podría conversar sobre el control e inventario de mercadería de su negocio? Quisiera hacerle una consulta breve.`}
};
function patch(id){const l=(window.INVENTORY_LEADS||[]).find(x=>x.id===id),m=document.getElementById('modal');if(!l||!m)return;const h=[...m.querySelectorAll('h3')].find(x=>x.textContent.trim()==='Mensaje inicial'),block=h?.closest('.block');if(!block)return;const tabs=block.querySelector('.variantTabs'),help=block.querySelector('.variantHelp'),ta=block.querySelector('#msgBox');if(!tabs||!ta)return;const saved=get(),v=P[saved[id]]?saved[id]:'A';tabs.innerHTML=Object.entries(P).map(([k,x])=>`<button type="button" class="variantBtn ${k===v?'on':''}" data-v78="${k}">${k} · ${x.name}</button>`).join('');if(help)help.textContent=P[v].help;ta.value=P[v].text(l);tabs.querySelectorAll('[data-v78]').forEach(b=>b.onclick=()=>{const x=get();x[id]=b.dataset.v78;localStorage.setItem(KEY,JSON.stringify(x));patch(id)});
 const send=[...block.querySelectorAll('a.btn')].find(a=>/WhatsApp/i.test(a.textContent));if(send)send.href=`https://wa.me/${String(l.whatsapp||'').replace(/\D/g,'').replace(/^51(?=9\d{8}$)/,'') .replace(/^(9\d{8})$/,'51$1')}?text=${encodeURIComponent(ta.value)}`;
 ta.oninput=()=>{if(send)send.href=send.href.split('?')[0]+'?text='+encodeURIComponent(ta.value)};
}
function boot(){const old=window.openLead;if(typeof old!=='function'||old.__v78)return;function wrapped(id){old(id);setTimeout(()=>patch(id),45)}wrapped.__v78=true;window.openLead=wrapped}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,700);
})();